# Generated by Django 2.2 on 2021-02-23 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('kategori', models.CharField(max_length=255)),
                ('kode_barang', models.CharField(max_length=255)),
                ('nama_barang', models.CharField(max_length=255)),
                ('harga_beli', models.DecimalField(decimal_places=2, max_digits=15)),
                ('harga_jual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('diskon', models.DecimalField(decimal_places=0, max_digits=15)),
                ('stok', models.DecimalField(decimal_places=0, max_digits=5)),
                ('lokasi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cus', models.CharField(max_length=10, unique=True)),
                ('nama_cus', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('no_tlp', models.CharField(max_length=255)),
                ('kota', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_nota', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('qty', models.DecimalField(decimal_places=0, max_digits=5)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('laba', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sisa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laku', to='kasir.Barang')),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_suplier', models.CharField(max_length=10, unique=True)),
                ('nama_suplier', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('no_tlp', models.CharField(max_length=255)),
                ('rek_bank', models.CharField(max_length=255)),
                ('pemilik_rek', models.CharField(max_length=255)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='kasir.Barang')),
            ],
        ),
    ]
